// AUTH
const LOGIN = 'LOGIN';
const SIGN_UP = 'SIGN_UP';
const LOGOUT = 'LOGOUT';
// SNACKBAR
const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
// POST
const SET_POSTLIST = 'SET_POSTLIST';
//  Exporting action types
export {
	// AUTH
	SIGN_UP,
	LOGIN,
	LOGOUT,
	// SNACKBAR
	SHOW_SNACKBAR,
	CLOSE_SNACKBAR,
	// POST
	SET_POSTLIST,
};
